# Generated by Django 6.1 on 2026-08-18 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCheck',
            fields=[
                ('checklist_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='체크리스트 ID')),
                ('check_date', models.DateField(verbose_name='체크 일자')),
                ('uv_protection_yn', models.BooleanField(default=False, verbose_name='자외선 차단제 사용 여부')),
                ('regen_cream_yn', models.BooleanField(default=False, verbose_name='재생크림 사용 여부')),
                ('smoking_yn', models.BooleanField(default=False, verbose_name='흡연 여부')),
                ('drinking_yn', models.BooleanField(default=False, verbose_name='음주 여부')),
                ('intense_exercise_yn', models.BooleanField(default=False, verbose_name='격한 운동 여부')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_checks', to=settings.AUTH_USER_MODEL, verbose_name='사용자 ID')),
            ],
            options={
                'verbose_name': '데일리 체크리스트',
                'verbose_name_plural': '데일리 체크리스트 목록',
                'db_table': 'dailycheck',
                'unique_together': {('user', 'check_date')},
            },
        ),
    ]
