# Generated by Django 6.1 on 2026-08-16 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='카테고리명')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('proc_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='시술 코드')),
                ('proc_name', models.CharField(max_length=50, verbose_name='시술명')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='proc.category', verbose_name='카테고리')),
            ],
        ),
    ]
