# Generated by Django 6.1 on 2026-08-16 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='category_id',
            new_name='category',
        ),
    ]
