# Generated by Django 6.1 on 2026-08-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0002_rename_category_id_procedure_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='proc_duration',
            field=models.PositiveIntegerField(default=1, help_text='지속 기간(개월 단위, 예: 1, 6, 12)', verbose_name='지속기간(개월)'),
            preserve_default=False,
        ),
    ]
