# Generated by Django 6.1 on 2026-08-17 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0003_procedure_proc_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureRecord',
            fields=[
                ('record', models.BigAutoField(primary_key=True, serialize=False, verbose_name='기록 ID')),
                ('proc_name', models.CharField(max_length=100, verbose_name='시술명')),
                ('procedure_date', models.DateField(verbose_name='시술 날짜')),
                ('hospital_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='병원명')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='시술 관련 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('procedure', models.ForeignKey(db_column='proc_code', on_delete=django.db.models.deletion.PROTECT, related_name='records', to='proc.procedure', verbose_name='시술 코드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_records', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '시술 기록',
                'verbose_name_plural': '시술 기록 목록',
                'db_table': 'procedure_record',
                'ordering': ['-procedure_date', '-created_at'],
            },
        ),
    ]
