# Generated by Django 6.1 on 2026-08-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proc', '0004_auto_20260818_1704'),
        ('proc', '0004_procedurerecord'),
    ]

    operations = [
    ]
