# Generated by Django 6.1 on 2026-08-19 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proc', '0004_procedurerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.PositiveIntegerField(verbose_name='분석 ID')),
                ('category_code', models.CharField(max_length=30, verbose_name='카테고리 코드 스냅샷')),
                ('elapsed_days', models.PositiveIntegerField(verbose_name='시술 후 경과일')),
                ('a_d', models.FloatField(verbose_name='A(D) - 오늘 CV 실측치 평균')),
                ('e_d', models.FloatField(verbose_name='E(D) - 기대 감쇠치')),
                ('base_index_value', models.FloatField(verbose_name='기본 보존지수')),
                ('checklist_adjustment', models.IntegerField(verbose_name='체크리스트 보정치')),
                ('final_index_value', models.FloatField(verbose_name='최종 보존지수')),
                ('checklist_snapshot', models.JSONField(blank=True, default=dict, verbose_name='체크리스트 스냅샷 (더미)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='산출 일시')),
                ('procedure_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preservation_indices', to='proc.procedurerecord', verbose_name='시술 기록')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preservation_indices', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '보존지수',
                'verbose_name_plural': '보존지수 목록',
                'db_table': 'preservation_index',
                'ordering': ['-calculated_at'],
            },
        ),
    ]
