# Generated by Django 6.1 on 2026-08-14 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SelfieAnalysis",
            fields=[
                ("analysis_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("captured_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "분석 대기/진행 중"),
                            ("SUCCESS", "분석 성공"),
                            ("FAIL", "분석 실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "fail_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_FACE", "얼굴 미검출"),
                            ("MULTIPLE_FACES", "다중 얼굴"),
                            ("MASK_DETECTED", "마스크 착용"),
                            ("MOTION_BLUR", "흔들림"),
                            ("IMAGE_TOO_LARGE", "용량 초과"),
                            ("UPLOAD_FAILED", "업로드 실패"),
                            ("API_ERROR", "API 오류"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "provider_file_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "provider_task_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "selfie_analysis",
            },
        ),
        migrations.CreateModel(
            name="SelfieAnalysisDetail",
            fields=[
                ("detail_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("face_part_code", models.CharField(max_length=30)),
                ("metric_code", models.CharField(max_length=30)),
                ("metric_value", models.DecimalField(decimal_places=2, max_digits=6)),
                ("metric_unit", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        db_column="analysis_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="analysis.selfieanalysis",
                    ),
                ),
            ],
            options={
                "db_table": "selfie_analysis_detail",
            },
        ),
    ]
