# Generated by Django 6.1 on 2026-08-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfieanalysisdetail',
            name='face_part_code',
        ),
        migrations.AlterField(
            model_name='selfieanalysis',
            name='fail_reason',
            field=models.CharField(blank=True, choices=[('NO_FACE', '얼굴 미검출'), ('MULTIPLE_FACES', '다중 얼굴'), ('MASK_DETECTED', '마스크 착용'), ('MOTION_BLUR', '흔들림'), ('FACE_TOO_SMALL', '얼굴 너무 작음'), ('IMAGE_TOO_LARGE', '용량 초과'), ('UPLOAD_FAILED', '업로드 실패'), ('API_ERROR', 'API 오류')], max_length=50, null=True),
        ),
    ]
