# Generated by Django 6.1 on 2026-08-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_selfieanalysisdetail_face_part_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfieanalysis',
            name='provider_task_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
