# Generated by Django 6.1 on 2026-08-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_selfieanalysis_provider_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfieanalysis',
            name='provider_task_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
